race/main_app/urls.py
from django.conf.urls import url
from main_app import views

#TEMPLATE TAGGING
app_name =  'main_app'


urlpatterns = [
    url(r'^about/$',views.about_view,name='about'),
    url(r'^register/$',views.register_view,name='register'),
    url(r'^results/$',views.results_view,name='results'),
    url(r'^route/$',views.route_view,name='route'),


]

race/race/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from main_app import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^main_app/',include('main_app.urls'))
]

race/main_app/models.py
from django.db import models
import datetime


DOCUMENT_CHOICES = (
    ('C.C.', 'CÉDULA DE CIUDADANÍA'),
    ('C.E.', 'CÉDULA DE EXTRANJERIA'),
    ('C.I.P.', 'CÉDULA DE IDENTIDAD POLICIAL'),
    ('C.M.', 'CÉDULA MILITAR'),
    ('C.E.I.L.', 'CÓD. ESTUDIANTE I.LENGUAS'),
    ('C.EST.', 'CÓDIGO ESTUDIANTE'),
    ('C.REG.', 'CONTRASEÑA REGISTRADURIA'),
    ('E.EXT.', 'ENTIDADES EXTRANJERAS'),
    ('L.M.', 'LIBRETA MILITAR'),
    ('NIT', 'NIT'),
    ('OTHERS', 'OTROS DOCUMENTOS'),
    ('PASSPORT', 'PASAPORTE'),
    ('C.PASSPORT', 'PASAPORTE COLOMBIANO'),
    ('R.C.', 'REGISTRO CIVIL'),
    ('R.C.', 'SIN DOCUMENTO'),
    ('T.I.', 'TARJETA DE IDENTIDAD'),
    ('TAX ID', 'TAX ID/NÚMERO DE IMPUESTO PARA'),
    ('VAT', 'VAT/NÚMERO DE IMPUESTO PARA PR'),
)

GENDER_CHOICES = (
    ('ML','MASCULINO'),
    ('FM','FEMENINO'),
    ('OTHER','OTRO'),
)

B_TYPE_CHOICES = (
    ('O-','O -'),
    ('O+','O +'),
    ('A-','A -'),
    ('A+','A +'),
    ('B-','B -'),
    ('B+','B +'),
    ('AB-','AB -'),
    ('AB+','AB +'),


)
# Create your models here.
class Runner(models.Model):
    document_type = models.CharField(max_length=128,choices=DOCUMENT_CHOICES,default='CC')
    document_number = models.CharField(max_length=128)
    first_name = models.CharField(max_length=128)
    second_name = models.CharField(max_length=128,blank=True)
    first_lastname = models.CharField(max_length=128)
    second_lastname = models.CharField(max_length=128)
    cellphone = models.CharField(max_length=128,unique=True)
    address = models.CharField(max_length=128)
    email = models.EmailField(max_length=264,unique=True)
    gender = models.CharField(max_length=128,choices=GENDER_CHOICES,default='ML')
    health = models.CharField(max_length=128)
    birth = models.DateField(default=datetime.date.today)
    blood_type = models.CharField(max_length=128,choices=B_TYPE_CHOICES,default='O-')
    emergency_contact = models.CharField(max_length=128)
    emergency_contact_cellphone = models.CharField(max_length=128)
    number = models.PositiveIntegerField(default=0)
    time = models.TimeField(null=True)
    class Meta:
        unique_together = ('document_type','document_number')

#class StudentUISRunner(Runner):

race/main_app/forms.py
from django import forms
from main_app.models import Runner

class NewRunnerForm(forms.ModelForm):

    class Meta():
        model = Runner
        exclude = ['number','time']
        labels = {'document_type':'Tipo de documento',
                'document_number':'Número de documento',
                'first_name':'Primer nombre',
                'second_name':'Segundo nombre',
                'first_lastname':'Primer apellido',
                'second_lastname':'Segundo apellido',
                'cellphone':'Número de celular',
                'address':'Dirección',
                'email':'Correo electrónico',
                'gender':'Sexo',
                'health':'EPS',
                'birth':'Fecha de nacimiento',
                'blood_type':'Tipo de sangre',
                'emergency_contact':'Nombre contacto de emergencia',
                'emergency_contact_cellphone':'Número de télefono contacto'}


class ConsultForm(forms.Form):
    number = forms.IntegerField()

race/main_app/views.py
from django.shortcuts import render
#from django.http import HttpResponse
# Create your views here.
from main_app.forms import NewRunnerForm,ConsultForm
from main_app.models import Runner


def index(request):
    return render(request,'main_app/index.html')

def about_view(request):
    return render(request,'main_app/about.html')

def register_view(request):
    form = NewRunnerForm()
    if request.method == "POST":
        print('holi')
        form = NewRunnerForm(request.POST)

        if form.is_valid():
            runner = form.save(commit=False)
            ###AGREGAR NUMERO DE CORREDOR
            runner.number=1000
            runner.save()
        else:
            print('ERROR')
    form = NewRunnerForm()
    return render(request,'main_app/register.html',{'form':form})

def results_view(request):
    form = ConsultForm()
    runner_dict = {'runner_data':''}
    runner=''
    if request.method == "POST":
        form = ConsultForm(request.POST)

        if form.is_valid():
            number=form.cleaned_data['number']
            try:
                runner=Runner.objects.get(number=number)
                runner_dict = {'runner_data':runner}

            except Exception as e:
                pass

        else:
            print('ERROR')
    #return render(request,'main_app/results.html',{'form':form})
    return render(request,'main_app/results.html',context={'form':form,'runner_data':runner})

def route_view(request):
    return render(request,'main_app/route.html')

race/templates/main_app/about.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
    <h1>ACERCA DE</h1>
    {% endblock %}

race/templates/main_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static "images/logo.jpg" %}" width="50" height="40" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Inicio <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:about' %}">Acerca de la carrera</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:route' %}">Recorrido</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:register' %}">Inscripción</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main_app:results' %}">Resultados</a>
      </li>

    </ul>
  </div>
</nav>


<div class="container">

  {% block body_block %}

  <!--Todo lo que este afuera será heredado -->

  {% endblock %}

</div>



    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

race/templates/main_app/index.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
    <h1>PRINCIPAL</h1>
    {% endblock %}

race/templates/main_app/register.html
<!DOCTYPE html>

{% extends "main_app/base.html" %}
  {% block body_block %}



    <form method="POST">
        {{ form.as_p }}

        {% csrf_token %}
        <input type="submit" class="btn btn-success" value="Resgistrar">
    </form>

    {% endblock %}

race/templates/main_app/results.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
    <h1>RESULTADOS</h1>
    <div class="container">
      <form method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-success" value="Submit">
      </form>
      <div class="container">

        {% if runner_data %}

          <ul>
            <li>{{ runner_data.first_name }}</li>
            <li>{{ runner_data.first_lastname }}</li>
          </ul>
        {% else %}
            <p>No existe el corredor</p>
            {{ runner_data.first_name }}

        {% endif %}

      </div>


    </div>
    {% endblock %}

race/templates/main_app/route.html
<!DOCTYPE html>
{% extends "main_app/base.html" %}
  {% block body_block %}
    <h1>RUTA</h1>
    {% endblock %}